apiVersion: v1
kind: Namespace
metadata:
  name: service-instances
---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    secretgen.carvel.dev/image-pull-secret: ""
  name: tap-registry
  namespace: service-instances
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: e30K
